### ISSUE TITLE
Entry with configurationId [object Object] doesn't exist

### ISSUE THREAD

**Issue by MaisonMisechy** [saleor/saleor-app-payment-stripe#130]
After creating a configuration, whatever the name I chose, I get an error when assigning my Stripe configurations to a Saleor channel.

https://github.com/saleor/saleor-app-payment-stripe/assets/143103701/d414d5d2-d373-42c5-bd3c-92b1ea1a11d6

I'm using a self-hosted Saleor instance, with a self hosted plugin, everything running on localhost.
I tried tunneling the app, but it did the same error.

Here's the entire log message I get from the dashboard:

```{
  "message": "Entry with configurationId [object Object] doesn't exist",
  "code": -32603,
  "data": {
    "code": "INTERNAL_SERVER_ERROR",
    "httpStatus": 500,
    "stack": "EntryDoesntExistError: Entry with configurationId [object Object] doesn't exist\n    at setMappingInAppConfig (webpack-internal:///(api)/./src/modules/payment-app-configuration/mapping-manager.ts:76:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async resolveMiddleware (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:417:30)\n    at async callRecursive (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:453:32)\n    at async outputMiddleware (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:298:24)\n    at async callRecursive (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:453:32)\n    at async callRecursive (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:453:32)\n    at async callRecursive (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:453:32)\n    at async callRecursive (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:453:32)\n    at async callRecursive (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:453:32)\n    at async resolve (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:483:24)\n    at async inputToProcedureCall (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/resolveHTTPResponse-3aef2178.mjs:46:22)\n    at async Promise.all (index 0)\n    at async resolveHTTPResponse (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/resolveHTTPResponse-3aef2178.mjs:173:37)\n    at async file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/nodeHTTPRequestHandler-842a1461.mjs:67:9\n    at async file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/adapters/next.mjs:44:9",
    "path": "paymentAppConfigurationRouter.mapping.update",
    "serialized": {
      "trpcCode": "INTERNAL_SERVER_ERROR",
      "fieldName": "configurationId",
      "name": "EntryDoesntExistError",
      "message": "Entry with configurationId [object Object] doesn't exist",
      "stack": "EntryDoesntExistError: Entry with configurationId [object Object] doesn't exist\n    at setMappingInAppConfig (webpack-internal:///(api)/./src/modules/payment-app-configuration/mapping-manager.ts:76:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async resolveMiddleware (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:417:30)\n    at async callRecursive (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:453:32)\n    at async outputMiddleware (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:298:24)\n    at async callRecursive (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:453:32)\n    at async callRecursive (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:453:32)\n    at async callRecursive (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:453:32)\n    at async callRecursive (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:453:32)\n    at async callRecursive (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:453:32)\n    at async resolve (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/index.mjs:483:24)\n    at async inputToProcedureCall (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/resolveHTTPResponse-3aef2178.mjs:46:22)\n    at async Promise.all (index 0)\n    at async resolveHTTPResponse (file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/resolveHTTPResponse-3aef2178.mjs:173:37)\n    at async file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/nodeHTTPRequestHandler-842a1461.mjs:67:9\n    at async file:///C:/Users/Spl3en/AppData/Local/Temp/tmp/saleor-app-payment-stripe/node_modules/.pnpm/registry.npmjs.org+@trpc+server@10.37.1/node_modules/@trpc/server/dist/adapters/next.mjs:44:9"
    }
  }
}
```

**Comment by MaisonMisechy** [comment]
It looks like the bug is coming from a wrong handling of the `Combobox` onChange event. I'm using the v0.2.0 tag.

See the fix here:

https://github.com/MaisonMisechy/saleor-app-payment-stripe/commit/014b8f2bd5be414c1edd283097a2bd3ec1532a6b

**Comment by jgun** [comment]
@MaisonMisechy You saved my day. This patch resolved the issue.

**Comment by naseef0** [comment]
> v0.2.0 tag.

I'm still have the same issue

**Comment by MaisonMisechy** [comment]
> I'm still have the same issue

Pleasee see the link to the fix I mentionned in https://github.com/saleor/saleor-app-payment-stripe/issues/130#issuecomment-1699430727

**Comment by mmiszy** [comment]
Fixed in https://github.com/saleor/saleor-app-payment-stripe/pull/131
